export const DATA_LOADED = 'DATA_LOADED';
export const UPDATE_PLANETS_COUNT = 'UPDATE_PLANETS_COUNT';
/* export const UPDATE_PLANETS = 'UPDATE_PLANETS';
export const INSERT_PLANETS = 'INSERT_PLANETS';
export const DELETE_PLANETS = 'DELETE_PLANETS'; */
